const data = {
  id: 45,
  projectName: "भदोही के औराई के चक मजूद में पाईप पेयजल योजना",
  projectStatus: "2",
  projectDepartment: "अल्पसंख्यक कल्याण एवं वक्फ",
  executingAgency:
    "उत्तर प्रदेश राज्य निर्माण एवं श्रम विकास सहकारी संघ लिमिटेड",
  scheme: null,
  projectSanctionDate: "2019-09-03T18:30:00.000Z",
  projectFinancialApprovalGoNumber: null,
  projectFinancialApprovalDate: null,
  actualProjectStartDate: "2020-05-19T18:30:00.000Z",
  projectCompletionDate: "2024-03-30T18:30:00.000Z",
  revisedProjectSanctionDate: null,
  revisedProjectCompletionDate: "2024-10-30T18:30:00.000Z",
  estimatedCompletionDate: null,
  actualCompletionDate: null,
  workOrderFormationDate: null,
  landHandoverDate: null,
  lastUpdatedDate: null,
  lastUpdatedDateOnCmis: null,
  totalApprovedBudget: "12900000.00",
  revisedProjectCost: null,
  lastMonthPhysicalProgress: null,
  currentMonthPhysicalProgress: null,
  totalReleasedFunds: "12900000.00",
  totalExpenditure: "9900000.00",
  lastFundReceivedDate: null,
  utilizationCertificateSubmissionDate: "2021-07-24",
  geoTaggedPhotosLastMonth: null,
  geoTaggedPhotosCurrentMonth: null,
  meetingDescription: null,
  meetingCompliance: null,
  meetingfeedback: "कार्य प्रगति पर",
};
