CREATE DATABASE IF NOT EXISTS testing;
USE testing;


CREATE TABLE `projects` (
  `id` int NOT NULL AUTO_INCREMENT,
  `project_name` varchar(255) NOT NULL,
  `project_status` varchar(50) DEFAULT NULL,
  `project_goal` text,
  `project_department` varchar(255) DEFAULT NULL,
  `department_id` int DEFAULT NULL,
  `executing_agency` varchar(255) DEFAULT NULL,
  `executing_agency_id` int DEFAULT NULL,
  `scheme` varchar(255) DEFAULT NULL,
  `description` text,
  `fund_sanctioned_by` varchar(255) DEFAULT NULL,
  `concerned_official_name` text,
  `concerned_project_manager` text,
  `project_sanction_date` date DEFAULT NULL,
  `project_financial_approval_go_number` varchar(255) DEFAULT NULL,
  `project_financial_approval_date` date DEFAULT NULL,
  `actual_project_start_date` date DEFAULT NULL,
  `project_completion_date` date DEFAULT NULL,
  `revised_project_sanction_date` date DEFAULT NULL,
  `revised_project_completion_date` date DEFAULT NULL,
  `estimated_completion_date` date DEFAULT NULL,
  `actual_completion_date` date DEFAULT NULL,
  `work_order_formation_date` date DEFAULT NULL,
  `land_handover_date` date DEFAULT NULL,
  `contact_information` int DEFAULT NULL,
  `last_updated_date` datetime DEFAULT NULL,
  `last_updated_date_on_cmis` datetime DEFAULT NULL,
  `project_handover_date` date DEFAULT NULL,
  `project_handover_to` varchar(255) DEFAULT NULL,
  `parallel_requirements` text,
  `total_approved_budget` decimal(15,2) DEFAULT NULL,
  `revised_project_cost` decimal(15,2) DEFAULT NULL,
  `approved_project_cost` decimal(15,2) DEFAULT NULL,
  `contract_date` date DEFAULT NULL,
  `contract_cost` decimal(15,2) DEFAULT NULL,
  `total_released_funds` text,
  `total_expenditure` text,
  `delay_reason` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;